import {
  collection,
  doc,
  getDocs,
  getDoc,
  setDoc,
  query,
  orderBy
} from 'firebase/firestore';
import { db } from './config';
import { USERS_COLLECTION } from './userService';
import {
  EmergencySession,
  CreateEmergencySessionInput
} from '../../types/emergency';

/**
 * Subcollection name for emergency sessions
 */
export const SESSIONS_SUBCOLLECTION = 'emergencySessions';

/**
 * Helper to generate subcollection path `users/{userId}/emergencySessions`
 */
const getSessionsCollectionRef = (userId: string) => {
  if (!userId) {
    throw new Error('[EmergencyService] UserId is required.');
  }
  return collection(db, USERS_COLLECTION, userId, SESSIONS_SUBCOLLECTION);
};

/**
 * Helper to generate document reference `users/{userId}/emergencySessions/{sessionId}`
 */
const getSessionDocRef = (userId: string, sessionId: string) => {
  if (!userId || !sessionId) {
    throw new Error('[EmergencyService] UserId and SessionId are required.');
  }
  return doc(db, USERS_COLLECTION, userId, SESSIONS_SUBCOLLECTION, sessionId);
};

/**
 * Saves a new emergency session result (e.g. generated by Member 1's AI Decision Engine) to Firestore.
 */
export const saveEmergencySession = async (
  userId: string,
  sessionData: CreateEmergencySessionInput
): Promise<EmergencySession> => {
  if (!userId) {
    throw new Error('[EmergencyService] Cannot save emergency session: UserId is required.');
  }
  if (!sessionData.emergencyType || !sessionData.severity || !sessionData.summary) {
    throw new Error('[EmergencyService] Emergency type, severity, and summary are required.');
  }

  const sessionsRef = getSessionsCollectionRef(userId);
  const newSessionRef = doc(sessionsRef);
  const now = new Date().toISOString();

  const newSession: EmergencySession = {
    id: newSessionRef.id,
    userId,
    emergencyType: sessionData.emergencyType,
    severity: sessionData.severity,
    summary: sessionData.summary,
    userPrompt: sessionData.userPrompt || '',
    immediateActions: Array.isArray(sessionData.immediateActions) ? sessionData.immediateActions : [],
    avoidInstructions: Array.isArray(sessionData.avoidInstructions) ? sessionData.avoidInstructions : [],
    escalationRequired: !!sessionData.escalationRequired,
    needsLocation: !!sessionData.needsLocation,
    professionalHelpRecommended: !!sessionData.professionalHelpRecommended,
    location: sessionData.location || null,
    timestamp: now,
  };

  try {
    await setDoc(newSessionRef, newSession);
    return newSession;
  } catch (error: any) {
    console.error('[EmergencyService] Failed to save emergency session:', error?.message || error);
    throw new Error(`Failed to save emergency session: ${error?.message || 'Unknown error'}`);
  }
};

/**
 * Retrieves past emergency history for a given user ordered by timestamp descending.
 */
export const getEmergencyHistory = async (userId: string): Promise<EmergencySession[]> => {
  if (!userId) {
    throw new Error('[EmergencyService] Cannot fetch emergency history: UserId is required.');
  }

  try {
    const sessionsRef = getSessionsCollectionRef(userId);
    const q = query(sessionsRef, orderBy('timestamp', 'desc'));
    const snapshot = await getDocs(q);

    const history: EmergencySession[] = [];
    snapshot.forEach((docSnap) => {
      history.push(docSnap.data() as EmergencySession);
    });

    return history;
  } catch (error: any) {
    console.error('[EmergencyService] Failed to fetch emergency history:', error?.message || error);
    throw new Error(`Failed to retrieve emergency history: ${error?.message || 'Unknown error'}`);
  }
};

/**
 * Retrieves a single emergency session by ID.
 */
export const getEmergencySession = async (
  userId: string,
  sessionId: string
): Promise<EmergencySession | null> => {
  try {
    const sessionRef = getSessionDocRef(userId, sessionId);
    const docSnap = await getDoc(sessionRef);

    if (docSnap.exists()) {
      return docSnap.data() as EmergencySession;
    }
    return null;
  } catch (error: any) {
    console.error('[EmergencyService] Failed to fetch emergency session:', error?.message || error);
    throw new Error(`Failed to retrieve emergency session: ${error?.message || 'Unknown error'}`);
  }
};

export default {
  saveEmergencySession,
  getEmergencyHistory,
  getEmergencySession,
};
